export const categories = [
  { value: "perennial", label: "Perennial" },
  { value: "shrubs", label: "Shrubs" },
  { value: "climbers", label: "Climbers" },
  { value: "bulbs", label: "Bulbs" },
  { value: "grasses", label: "Grasses" },
  { value: "flowers", label: "Flowers" },
  { value: "ferns", label: "Ferns" },
  { value: "fruit", label: "Fruit" },
  { value: "herbs", label: "Herbs" },
  { value: "vegetables", label: "Vegetables" },
  { value: "hedging", label: "Hedging" },
  { value: "trees", label: "Trees" },
  { value: "indoor-plants", label: "Indoor Plants" },
  { value: "soil", label: "Soil" },
  { value: "seeds", label: "Seeds" },
  { value: "household-supply", label: "Household Supply" },
  { value: "clothing", label: "Clothing" },
  { value: "lawn-tool", label: "Lawn Tools" },
  { value: "planting-tool", label: "Planting Tools" },
  { value: "paving-tool", label: "Paving Tools" },
  { value: "sports-tool", label: "Sports/Hobbies" },
  { value: "house-tool", label: "Household Tools" },
  { value: "maintenance-job", label: "Maintenance" },
  { value: "handyman-job", label: "General garden maintenance" },
  { value: "planting-job", label: "Planting" },
  { value: "paving-job", label: "Paving" },
  { value: "pond-job", label: "Pond maintenance" },
  { value: "cleaning-job", label: "Cleaning" },
  { value: "house-job", label: "Household Jobs" },
  { value: "building-job", label: "Building" },
  { value: "other-job", label: "Other" },
];
