export const itemCategories = [
  { value: "perennial", label: "Perennial" },
  { value: "shrubs", label: "Shrubs" },
  { value: "climbers", label: "Climbers" },
  { value: "bulbs", label: "Bulbs" },
  { value: "grasses", label: "Grasses" },
  { value: "flowers", label: "Flowers" },
  { value: "ferns", label: "Ferns" },
  { value: "fruit", label: "Fruit" },
  { value: "herbs", label: "Herbs" },
  { value: "vegetables", label: "Vegetables" },
  { value: "hedging", label: "Hedging" },
  { value: "trees", label: "Trees" },
  { value: "indoor-plants", label: "Indoor Plants" },
  { value: "soil", label: "Soil" },
  { value: "seeds", label: "Seeds" },
  { value: "household-supply", label: "Household Supply" },
  { value: "clothing", label: "Clothing" },
  { value: "other", label: "Other" },
];
